name: change-color-player
version: '${version}'
main: ru.mrsinkaaa.changecolorplayer.ChangeColorPlayer
api-version: '1.20'
commands:
  setcolor:
    description: Changes the player's name color
    usage: /setcolor <colorCode>
